# Generated by Django 4.0.5 on 2023-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
